--[[ 
    Date: 05/07/2025
    Day 2 of making this obfuscator ANTI TAMPER added esoecially for the 25ms dumper debugged and found a full bypass i formatted ita bit i aded string encryption but it kept breaking the code so removed it tommorow trying again
    TODO:
        -  STRING ENCRYPTION
--]]
return(function(...)do("This file was protected with Taxus Obfuscator"):gsub(".+",function()return "" end)end local A="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/" local function cropw(C)local D=2^18 local E=2^12 local F=2^6 local G=1 local H=256 local I=256^2 local K={}for L=1,#A do K[A:sub(L,L)]=L-1 end local N={}local O=1 while O<=#C do local P=C:sub(O,O)local Q=C:sub(O+1,O+1)local R=C:sub(O+2,O+2)local S=C:sub(O+3,O+3)local T=K[P]or 0 local U=K[Q]or 0 local V=K[R]or 0 local W=K[S]or 0 local X=T*D local Y=U*E local Z=V*F local aa=W*G local taxus=X+Y+Z+aa local ai=math.floor(taxus/I)local aj=math.floor((taxus%I)/H)local ak=taxus%H table.insert(N,string.char(ai))if R~="=" then table.insert(N,string.char(aj))end if S~="=" then table.insert(N,string.char(ak))end O=O+4 end return table.concat(N)end local ok1,info1=pcall(debug.getinfo,string.char,cropw("Uw=="))if ok1 and info1 and info1.what~=cropw("Qw==")then error(cropw("YnlwYXNzIHhkICJsaW5lIDE6IGF2ZXJhZ2UgLmwgdXNlciI="),0)end local jsh=math.rando m(1,999999)local function __t()return jsh end local ok2,info2=pcall(debug.getinfo,__t,cropw("Uw=="))if not(ok2 and info2 and info2.what==cropw("THVh"))then error(cropw("YnlwYXNzIHhkICJsaW5lIDE6IGF2ZXJhZ2UgLmwgdXNlciI="),0)end for i=1,10 do local ok,info=pcall(debug.getinfo,i,cropw("Uw=="))if ok and info then local s=info.source or cropw("")local w=info.what or cropw("")local sh=info.short_src or cropw("")if s:find(cropw("aHR0cGxvZw=="))or w:find(cropw("aHR0cGxvZw=="))or sh:find(cropw("aHR0cGxvZw=="))or s:find(cropw("bHVhdQ=="))or w:find(cropw("bHVhdQ=="))or sh:find(cropw("bHVhdQ=="))then error(cropw("YnlwYXNzIHhkICJsaW5lIDE6IGF2ZXJhZ2UgLmwgdXNlciI="),0)break end end end end)(...)


